<?php
/**
 * Unit tests for CartShare_DB.
 *
 * @package CartShare\Tests\Unit
 */

use PHPUnit\Framework\TestCase;

/**
 * In-memory wpdb replacement that honours the subset of the wpdb API used by
 * CartShare_DB.  All data is held in a private array keyed by table name.
 */
class Fake_WPDB {

	/** @var string WordPress table prefix. */
	public $prefix = 'wp_';

	/** @var string Last database error message. */
	public $last_error = '';

	/** @var int ID generated by the most recent insert(). */
	public $insert_id = 0;

	/** @var array Table storage: [ table_name => [ row, ... ] ] */
	private $storage = array();

	/** @var int Auto-increment counter. */
	private $next_id = 1;

	/**
	 * Return an empty charset/collate string.
	 *
	 * @return string
	 */
	public function get_charset_collate() {
		return '';
	}

	/**
	 * Insert a row into in-memory storage.
	 *
	 * @param string     $table  Table name.
	 * @param array      $data   Column => value pairs.
	 * @param array|null $format Ignored.
	 * @return int
	 */
	public function insert( $table, $data, $format = null ) {
		$data['id']   = $this->next_id++;
		$this->insert_id = $data['id'];
		if ( ! isset( $this->storage[ $table ] ) ) {
			$this->storage[ $table ] = array();
		}
		$this->storage[ $table ][] = $data;
		return 1;
	}

	/**
	 * Prepare a SQL statement by substituting %s/%d placeholders.
	 *
	 * @param string $sql  SQL with placeholders.
	 * @param mixed  ...$args Values.
	 * @return string
	 */
	public function prepare( $sql, ...$args ) {
		$i = 0;
		return preg_replace_callback(
			'/%[sd]/',
			function ( $m ) use ( &$i, $args ) {
				$v = $args[ $i++ ] ?? '';
				return $m[0] === '%s' ? "'" . addslashes( $v ) . "'" : (int) $v;
			},
			$sql
		);
	}

	/**
	 * Return a single row matching a WHERE token = '...' clause.
	 *
	 * @param string $sql    Prepared SQL.
	 * @param string $output Output format (ignored — always returns array).
	 * @return array|null
	 */
	public function get_row( $sql, $output = 'OBJECT' ) {
		if ( preg_match( "/WHERE token = '([^']+)'/", $sql, $m ) ) {
			$token = $m[1];
			foreach ( $this->storage as $rows ) {
				foreach ( $rows as $row ) {
					if ( isset( $row['token'] ) && $row['token'] === $token ) {
						return $row;
					}
				}
			}
		}
		return null;
	}

	/**
	 * Return multiple rows matching supported query patterns.
	 *
	 * Supports:
	 *  - find_expired: WHERE expires_at IS NOT NULL AND expires_at < ...
	 *  - list_for_user: WHERE user_id = N
	 *
	 * @param string $sql    Prepared SQL.
	 * @param string $output Output format (ignored).
	 * @return array|null
	 */
	public function get_results( $sql, $output = 'OBJECT' ) {
		// find_expired pattern.
		if ( false !== strpos( $sql, 'expires_at IS NOT NULL' ) && false !== strpos( $sql, 'expires_at <' ) ) {
			$now     = gmdate( 'Y-m-d H:i:s' );
			$results = array();
			foreach ( $this->storage as $rows ) {
				foreach ( $rows as $row ) {
					if ( ! empty( $row['expires_at'] ) && $row['expires_at'] < $now ) {
						$results[] = $row;
					}
				}
			}
			return $results ?: null;
		}

		// list_for_user pattern.
		if ( preg_match( '/WHERE user_id = (\d+)/', $sql, $m ) ) {
			$uid     = (int) $m[1];
			$results = array();
			foreach ( $this->storage as $rows ) {
				foreach ( $rows as $row ) {
					if ( isset( $row['user_id'] ) && (int) $row['user_id'] === $uid ) {
						$results[] = $row;
					}
				}
			}
			return $results ?: null;
		}

		return null;
	}

	/**
	 * Execute a direct query.
	 *
	 * Supports DELETE ... WHERE expires_at IS NOT NULL AND expires_at < ...
	 *
	 * @param string $sql SQL statement.
	 * @return int|false
	 */
	public function query( $sql ) {
		if ( false !== strpos( $sql, 'DELETE' ) && false !== strpos( $sql, 'expires_at' ) ) {
			$now   = gmdate( 'Y-m-d H:i:s' );
			$count = 0;
			foreach ( $this->storage as $table => &$rows ) {
				$before = count( $rows );
				$rows   = array_values(
					array_filter(
						$rows,
						function ( $row ) use ( $now ) {
							return empty( $row['expires_at'] ) || $row['expires_at'] >= $now;
						}
					)
				);
				$count += $before - count( $rows );
			}
			unset( $rows );
			return $count;
		}
		return false;
	}

	/**
	 * Delete rows matching WHERE criteria.
	 *
	 * @param string     $table        Table name.
	 * @param array      $where        Column => value pairs.
	 * @param array|null $where_format Ignored.
	 * @return int Number of rows deleted.
	 */
	public function delete( $table, $where, $where_format = null ) {
		if ( empty( $this->storage[ $table ] ) ) {
			return 0;
		}
		$before                   = count( $this->storage[ $table ] );
		$this->storage[ $table ]  = array_values(
			array_filter(
				$this->storage[ $table ],
				function ( $row ) use ( $where ) {
					foreach ( $where as $k => $v ) {
						if ( ! array_key_exists( $k, $row ) || $row[ $k ] !== $v ) {
							return true;
						}
					}
					return false;
				}
			)
		);
		return $before - count( $this->storage[ $table ] );
	}

	/**
	 * Return the number of rows in a table.
	 *
	 * @param string $table Table name.
	 * @return int
	 */
	public function row_count( $table ) {
		return count( $this->storage[ $table ] ?? array() );
	}
}

/**
 * Class Test_CartShare_DB
 *
 * Tests CartShare_DB CRUD operations against an in-memory wpdb fake.
 */
class Test_CartShare_DB extends TestCase {

	/** @var Fake_WPDB */
	protected $fake_wpdb;

	/** @var CartShare_DB */
	protected $db;

	/**
	 * Wire up the in-memory wpdb and create a fresh CartShare_DB instance.
	 *
	 * @return void
	 */
	protected function setUp(): void {
		parent::setUp();
		$this->fake_wpdb       = new Fake_WPDB();
		$GLOBALS['wpdb']       = $this->fake_wpdb;
		$this->db              = new CartShare_DB();
	}

	/**
	 * Clean up the global wpdb after each test.
	 *
	 * @return void
	 */
	protected function tearDown(): void {
		unset( $GLOBALS['wpdb'] );
		parent::tearDown();
	}

	/**
	 * insert() must return a 32-char token; find_by_token() must retrieve the row.
	 */
	public function test_insert_and_find_by_token_roundtrip() {
		$cart_data = array(
			'items'   => array(
				array(
					'product_id'    => 1,
					'quantity'      => 2,
					'variation_id'  => 0,
					'variation'     => array(),
					'cart_item_data'=> array(),
				),
			),
			'coupons' => array(),
		);

		$token = $this->db->insert( $cart_data, 1, null, 86400, 'My Cart' );

		$this->assertIsString( $token );
		$this->assertSame( 32, strlen( $token ) );

		$row = $this->db->find_by_token( $token );

		$this->assertNotNull( $row );
		$this->assertSame( $token, $row['token'] );

		$decoded = json_decode( $row['cart_data'], true );
		$this->assertSame( 1, $decoded['items'][0]['product_id'] );
	}

	/**
	 * find_by_token() must return null for a token that does not exist.
	 */
	public function test_find_by_token_returns_null_for_missing_token() {
		$result = $this->db->find_by_token( 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1' );
		$this->assertNull( $result );
	}

	/**
	 * find_expired() must return only the rows whose expiry has already passed.
	 */
	public function test_find_expired_returns_expired_rows() {
		$cart_data = array( 'items' => array(), 'coupons' => array() );

		// Insert a row that expired an hour ago.
		$token1 = $this->db->insert( $cart_data, null, null, -3600, null );
		// Insert a row that expires in the future.
		$this->db->insert( $cart_data, null, null, 86400, null );

		$expired = $this->db->find_expired();

		$this->assertCount( 1, $expired );
		$this->assertSame( $token1, $expired[0]['token'] );
	}

	/**
	 * delete_expired() must remove exactly the expired rows and leave others intact.
	 */
	public function test_delete_expired_removes_only_expired_rows() {
		$cart_data = array( 'items' => array(), 'coupons' => array() );

		$token1 = $this->db->insert( $cart_data, null, null, -3600, null );  // expired
		$token2 = $this->db->insert( $cart_data, null, null, 86400, null );  // future

		$count = $this->db->delete_expired();

		$this->assertSame( 1, $count );
		$this->assertNull( $this->db->find_by_token( $token1 ) );
		$this->assertNotNull( $this->db->find_by_token( $token2 ) );
	}
}
